/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuJugador;

import Mapeo.MapaVisual;
import com.formdev.flatlaf.intellijthemes.FlatXcodeDarkIJTheme;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javazoom.jl.decoder.JavaLayerException;
import musica.MusicaGenero;
import musica.ReproMusic;

/**
 *
 * @author chato
 */
public class ControlJugador extends javax.swing.JFrame {

    MusicaGenero GeneroMusica = new MusicaGenero("/musica/rock/R1.mp3", "musica/CumbiayBanda", "musica/ElectronicayOtros");
    String CarpetaRock = GeneroMusica.getRock();
    String CarpetaCumbias = GeneroMusica.getCumbias();
    String CarpetaElectronica = GeneroMusica.getElectronica();
    String RutaRock;
    ReproMusic repro = new ReproMusic();
    String canciones[] = new String[34];

    public ControlJugador() {
        initComponents();
        for (int i = 1; i <= 33; i++) {
            canciones[i] = "/musica/music/C" + i + ".mp3";
        }
        repro.pausa = true;
        try {
            repro.reproducir("/musica/music/C4.mp3");
            ImageIcon iconoGIF = new ImageIcon(getClass().getResource("/Gif/Menu.gif"));
            Image imagen = iconoGIF.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon iconoRedimensionado = new ImageIcon(imagen);
            jLabel3.setIcon(iconoRedimensionado);

            Timer timer = new Timer(4000, new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    jLabel3.setIcon(null); // Detener la animacion
                    ((Timer) evt.getSource()).stop(); // Detener el timer
                }
            });
        } catch (IOException ex) {
            Logger.getLogger(ControlJugador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JavaLayerException ex) {
            Logger.getLogger(ControlJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        reproButton = new javax.swing.JButton();
        mutebutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Nueva Partida");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Cargar Partida");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Opciones");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Salir");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 403, 60, 20));

        reproButton.setText("Cancion Aleatorea");
        reproButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproButtonActionPerformed(evt);
            }
        });
        jPanel1.add(reproButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 140, 20));

        mutebutton.setText("mute");
        mutebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mutebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(mutebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu/M1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 255, 440));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu/l2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, -4, 530, 450));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gif/menu.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 480, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reproButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproButtonActionPerformed
        repro.pausa = true;
        Random rand = new Random();
        int random = rand.nextInt(canciones.length);

        try {

            repro.reproducir(canciones[random]);
        } catch (IOException ex) {
            Logger.getLogger(ControlJugador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JavaLayerException ex) {
            Logger.getLogger(ControlJugador.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_reproButtonActionPerformed

    private void mutebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mutebuttonActionPerformed

        repro.togglePausa();
    }//GEN-LAST:event_mutebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            //ctrl + espacio para ver los diseños de ventana de la libreria de jTatto
//            UIManager.setLookAndFeel(new FlatDarculaLaf());
            FlatXcodeDarkIJTheme.setup();

        } catch (Exception ex) {
            Logger.getLogger(MapaVisual.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mutebutton;
    private javax.swing.JButton reproButton;
    // End of variables declaration//GEN-END:variables
}
